- job:
    name: os-autoinst-tox
    run: ci/tox.yaml
    nodeset: fedora-35-vm

- job:
    name: os-autoinst-perl
    run: ci/perl.yaml
    nodeset: fedora-35-vm

- project:
    check:
      jobs:
        - os-autoinst-tox
        - os-autoinst-perl
