- hosts: all
  tasks:
    - name: Install required packages
      package:
        name: ['os-autoinst', 'perl-Test-Strict', 'perl-Test-Harness', 'perl-JSON', 'perl-REST-Client']
        state: present
      become: yes
    - name: Run perl tests
      command: prove t/
      args:
        chdir: '{{ zuul.project.src_dir }}'
