- hosts: all
  tasks:
    - name: Include dnf dependency workaround task
      ansible.builtin.include_tasks:
        file: dnf-dependency.yaml
    - name: Ensure tox is installed
      include_role:
        name: ensure-tox
    - name: Install all Python versions to test
      package:
        name: ['python3.8', 'python3.9', 'python3.10', 'python3.11', 'python3.12']
        state: present
      become: yes
    - name: Run tox
      command: "{{ tox_executable }}"
      args:
        chdir: '{{ zuul.project.src_dir }}'
